name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
          
      - name: Install 
        run: yarn 
        
      - name: Build 
        run: yarn build
  
      - name: Build 
        run: yarn build
          
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "~/app/rentxapi"

      - name: Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/rentxapi
            yarn
            ./node_modules/.bin/typeorm migrations:run
            pm2 restart server

